CREATE TABLE awsx (
  id int(10) unsigned NOT NULL auto_increment,
  tstamp datetime NOT NULL,
  create_stamp timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  station varchar(255) NOT NULL,
  sms_counter int(11) NOT NULL,
  sample_interval int(11) NOT NULL,
  wind_avg float NOT NULL,
  wind_min float NOT NULL,
  wind_max float NOT NULL,
  wind_daily_max float NOT NULL,
  wind_dir int(11) NOT NULL,
  wind_stability int(11) NOT NULL,
  air_pressure int(11) NOT NULL,
  leaf_wetness int(11) NOT NULL,
  sun_radiation int(11) NOT NULL,
  temp_avg float NOT NULL,
  temp_daily_min float NOT NULL,
  temp_daily_max float NOT NULL,
  soil_temp float NOT NULL,
  rainfall float NOT NULL,
  rainfall_daily float NOT NULL,
  soil_moisture float NOT NULL,
  dewpoint float NOT NULL,
  humidity float NOT NULL,
  humidity_daily_min float NOT NULL,
  humidity_daily_max float NOT NULL,
  power_supply varchar(255) NOT NULL,
  battery_voltage float NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
